Post CRUD処理一式
Neko-Reset/kakeibo pull request #3
Opened 2022-05-10 12:35 UTC by DJ-phi

テスト追加

リレーション

userのshowに自分の投稿を表示

2022-05-15 16:45 UTC, ShunMinase requested changes
実装おつかれさまです！！！！！！全体的にいい感じでした！
細かい部分にはなりますが、いろいろとコメントをお付けしましたのでご確認お願いします……！

2022-05-15 16:45 UTC, ShunMinase commented on app/assets/stylesheets/home.scss
> +  background-image: url(https://i.pinimg.com/originals/61/49/ef/6149ef88a29d58e0006f4e1c1f3ef8ee.png);
そういえばこちらの画像、著作権に引っかかる可能性があるので、どこかのタイミングで差し替えましょう……！！！！笑

2022-05-15 16:45 UTC, ShunMinase commented on config/routes.rb
> +  resources:posts
そういえばpostsのindexとshowって不要なんでしたっけ……？？？
もし不要であれば、exceptを使って必要なルーティングのみに絞ってあげるのがおすすめです！(その場合、コントローラーのアクションとビューの削除、テストの削除もお願いします！)

2022-05-15 16:45 UTC, ShunMinase commented on config/application.rb
> +    config.time_zone = 'Tokyo'
あーー！！これも地味に大事な設定ですね……！！！
素晴らしいです！！！！！！

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/home_spec.rb
>    describe "GET /top" do
ログイン済の場合、家計簿にリダイレクトすることを検証するテストがあるとめちゃよいです……！

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/posts_spec.rb
> +    context "有効なパラメーターの場合" do
リダイレクト先を検証するテストと、有効でないパラメータを送信した場合のテストも追加してあげましょう……！(updateも同様)

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/posts_spec.rb
> +      it "new_post_pathにいけないようになっていること" do
ここと122行目と127行目のテストケースは、以下のように「ログインページにリダイレクトされること」を検証してあげれば大丈夫だと思われます！
```
get new_post_path
expect(response).to redirect_to(login_path)
```

これで132行目のテストケースが不要となり、コードが簡潔になります🙆‍♂️🙆‍♂️

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/posts_spec.rb
>  require 'rails_helper'
リクエストスペックだけでなく、spec/model/post_spec.rb(モデルスペック)の中身も作ってあげましょう……！

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/users_spec.rb
> +    context "有効なパラメーターの場合" do
無効なパラメータの場合のテストも定義してあげましょう🙆‍♂️

2022-05-15 16:45 UTC, ShunMinase commented on spec/requests/users_spec.rb
> +      it "新規作成ページにいけないようになっていること" do
ここと153行めのテストケースはほぼ同じことを検証しているので、以下のようにまとめてあげて大丈夫です🙆‍♂️🙆‍♂️
(159行目と165行目も同様)
```
get new_user_path
expect(response).to redirect_to(users_path)
```

2022-05-17 12:10 UTC, DJ-phi commented on app/controllers/application_controller.rb
> +      flash[:notice] = "すでにログインしています"
削除させていただきました！

2022-05-17 12:10 UTC, DJ-phi commented on app/controllers/posts_controller.rb
> +    set_post_user_id
不要なので削除しました！

2022-05-17 12:11 UTC, DJ-phi commented on app/controllers/users_controller.rb
> +  # before_action :ensure_correct_user, only: [:edit, :update] #動作確認がしたいので後ほど解放
todoでコメント入れました！

2022-05-17 12:11 UTC, DJ-phi commented on app/models/post.rb
> +  belongs_to :user, optional: true #リレーション, userは1の関係性, optional: trueとはbelongs_toの外部キーのnilを許可するというもの
不要なオプション削除しました！

2022-05-17 12:12 UTC, DJ-phi commented on app/models/post.rb
> +  validates :traffic, :food, format: { with: /\A[0-9]+\z/ }
オススメの記述に変更させていただきました！

2022-05-17 12:12 UTC, DJ-phi commented on app/models/post.rb
> +  def total_price
次のブランチで不要になるのでコメントアウトしました！

2022-05-17 12:12 UTC, DJ-phi commented on app/assets/stylesheets/home.scss
> +  background-image: url(https://i.pinimg.com/originals/61/49/ef/6149ef88a29d58e0006f4e1c1f3ef8ee.png);
最後に変えます😂

2022-05-17 12:13 UTC, DJ-phi commented on config/routes.rb
> +  resources:posts
どれが必要か最後までまだわからないので
保留しております😱

最後に絞ります🥶

2022-05-17 12:14 UTC, DJ-phi commented on spec/requests/home_spec.rb
>    describe "GET /top" do
追加しました！

2022-05-17 12:14 UTC, DJ-phi commented on spec/requests/posts_spec.rb
> +    context "有効なパラメーターの場合" do
追加しました！

2022-05-17 12:14 UTC, DJ-phi commented on spec/requests/posts_spec.rb
> +      it "new_post_pathにいけないようになっていること" do
まとめました！！

2022-05-17 12:20 UTC, DJ-phi commented on spec/requests/posts_spec.rb
>  require 'rails_helper'
追加しました！

2022-05-17 12:21 UTC, DJ-phi commented on spec/requests/users_spec.rb
> +    context "有効なパラメーターの場合" do
追加しました！！

2022-05-17 12:21 UTC, DJ-phi commented on spec/requests/users_spec.rb
> +      it "新規作成ページにいけないようになっていること" do
まとめました🧟‍♂️

2022-05-17 12:22 UTC, DJ-phi commented on app/models/user.rb
> +  has_many :posts, dependent: :destroy #リレーション,postsが多の関係性,dependent: :destroyはそのモデル(user)が削除されたら、紐づいているモデル(posts)も削除するというもの
追加しました！

2022-05-17 12:22 UTC, DJ-phi commented on config/application.rb
> +    config.time_zone = 'Tokyo'
ありがとう御座います！！

2022-05-18 15:27 UTC, ShunMinase approved these changes
修正おつかれさまです～～！LGTMです！！
Rspecの件も了解です！

2022-05-24 10:45 UTC, merged